### ISSUE TITLE
node-sass issue

### ISSUE THREAD

**Issue by ap-o** [icebob/vue-express-mongo-boilerplate#17]
It seems like i'm getting this issue
ERROR in ENOENT: no such file or directory, scandir '/Users/a/Workspace/vue-express-mongo-boilerplate/node_modules/node-sass/vendor'
 @ ./client/scss/style.scss 4:14-167 13:2-17:4 14:20-173

**Comment by ap-o** [comment]
Resolved by downgrading to node-sass 3.7.0

**Comment by icebob** [comment]
Great!
