### ISSUE TITLE
broken when rebuilding

### ISSUE THREAD

**Issue by HansHammel** [icebob/vue-express-mongo-boilerplate#28]
win 10 node 6.9.4
I fixed some webpack stuff, build runs without error now but still the smae messed up ui
![image](https://cloud.githubusercontent.com/assets/6475700/23582778/9d2ab9bc-0132-11e7-96a0-87b83f7ff597.png)
dev mode is working except some errors
![image](https://cloud.githubusercontent.com/assets/6475700/23582788/f41c7d8c-0132-11e7-8660-e1991b3a731e.png)

**Comment by icebob** [comment]
Could you make a PR with fix?

**Comment by HansHammel** [comment]
Sorry, I have no idea where there is something going wrong. I just wanted to learn vue by a more complex example, but this little puppy ruined by day  :cry:

**Comment by icebob** [comment]
If you have any new information about this issue, please reopen.
