### ISSUE TITLE
How can I integrate with twitter bootstrap 3?

### ISSUE THREAD

**Issue by lucduong** [icebob/vue-express-mongo-boilerplate#30]
Could you show me how can I integrate with twbs 3? (sass version)

**Comment by icebob** [comment]
I think, you need to use [bootstrap-loader](https://github.com/shakacode/bootstrap-loader)

**Comment by lucduong** [comment]
Thank you so much for replying.
I have done with this before.

I used `bootstrap-loader` like you said and add this one `bootstrap-loader/lib/bootstrap.loader?configFilePath=${bs3ConfigPath}/bs3.yml!bootstrap-loader/no-op.js`, to `entry.app` and this one to rules
```
// Bootstrap 3
      { 
				test: /bootstrap-sass\/assets\/javascripts\//, 
				use: 'imports-loader?jQuery=jquery'
			},
```

Thank you for your amazing project!
