### ISSUE TITLE
Error: spawn nodemon ENOENT

### ISSUE THREAD

**Issue by kosmos** [icebob/vue-express-mongo-boilerplate#31]
I get the following error:

➜ npm run dev

> vue-express-mongo-boilerplate@0.9.0 dev /Users/kosmos/Downloads/vue-express-mongo-boilerplate-master 2
> cross-env NODE_ENV=development nodemon --debug

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/kosmos/.nvm/versions/node/v6.9.4/bin/node" "/Users/kosmos/.nvm/versions/node/v6.9.4/bin/npm" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! vue-express-mongo-boilerplate@0.9.0 dev: `cross-env NODE_ENV=development nodemon --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-express-mongo-boilerplate@0.9.0 dev script 'cross-env NODE_ENV=development nodemon --debug'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-express-mongo-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development nodemon --debug
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-express-mongo-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-express-mongo-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kosmos/Downloads/vue-express-mongo-boilerplate-master 2/npm-debug.log

**Comment by icebob** [comment]
Please try `npm install -g nodemon`

**Comment by kosmos** [comment]
Thank you! It have helped. And thank you for such a good boilerplate!
