### ISSUE TITLE
Nodemon restart takes 1-2 minutes

### ISSUE THREAD

**Issue by fizerkhan** [icebob/vue-express-mongo-boilerplate#32]
Everytime I make changes, the node server restarts through `nodemon` service and then UI reloads. But I have to wait around 1-2 minutes to server to come back as well as UI reload.

This is become cumbersome when making small changes during development. Is there any way to reduce the restart time? Because it is affecting my productivity too much.

**Comment by icebob** [comment]
JS files separated to two parts. `server` and `clients`. If you modify server codes nodemon restart server. But when restarting, client-side websocket disconnected. After server restart, the websocket will be established, and will refresh page. You can turn off this full page refresh in [App.vue](https://github.com/icebob/vue-express-mongo-boilerplate/blob/master/client/app/core/App.vue#L72)

**Comment by fizerkhan** [comment]
@icebob Thanks. I will try.
