### ISSUE TITLE
Issue in pug variables in head parts

### ISSUE THREAD

**Issue by fizerkhan** [icebob/vue-express-mongo-boilerplate#35]
In the `head.pug`, the app variables do not placed in meta tags properly.

This line 

```
meta(name='keywords', content='#{app.keywords}')
```
should be 
```
meta(name='keywords', content=app.keywords)
```

Following lines have to changed.

https://github.com/icebob/vue-express-mongo-boilerplate/blob/master/server/views/parts/head.pug#L8:L23

**Comment by icebob** [comment]
Nice observation. Could you make a PR with fix?

**Comment by fizerkhan** [comment]
Yes, I will do it.
