### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by zeroby0** [icebob/vue-express-mongo-boilerplate#39]
Hi :)
I'm fairly new to development with nodejs, it would be really helpful if you could include how to use the project. Like what each file/folder means and how to modify them. And how to setup a basic website with this.

I'm looking for a vuejs front end and a graphql backend, decoupled so that I can reuse the API.  
Thank you

**Comment by icebob** [comment]
Sorry, but currently I have no free time to make a docs about usage.

**Comment by sw-yx** [comment]
@icebob i might. i really love what you have done here. @zeroby0 this project wont suite you since it uses a mongo backend.
