### ISSUE TITLE
Cannot find module 'Moleculer'

### ISSUE THREAD

**Issue by lrossy** [icebob/vue-express-mongo-boilerplate#41]
Small issue I found on the ice-services branch that only happens when i use on Debian (through Docker)

```
info:   Load www/service
debug: [BROKER] Event emitted: register.service.metrics
error: uncaughtException: Cannot find module 'Moleculer'
```

Fixed by changing 

let Context		= require("Moleculer").Context;

to 

let Context		= require("moleculer").Context;

in server/services/www/service.js

This error does not happen for me when i run though webStorm in windows however so perhaps it could be something on my end?

**Comment by icebob** [comment]
Ohh, thanks., The problem is that the case-sensitive name. The correct package name is `moleculer`. And on windows it's working with `Moleculer` too. Thanks, I will fix it.
