### ISSUE TITLE
Small bug on posts/service.js

### ISSUE THREAD

**Issue by lrossy** [icebob/vue-express-mongo-boilerplate#43]
`ice-services` branch

https://github.com/icebob/vue-express-mongo-boilerplate/blob/ice-services/server/services/applogic/posts/service.js#L44

error: [WWW-SVC] Request error:  { TypeError: Cannot read property 'id' of undefined
    at APIService.handler (server\services\applogic\posts\service.js:45:29)

to fix. change from 
`filter.author = ctx.user.id;`
to 
`filter.author =ctx.params.$user.id;`

**Comment by icebob** [comment]
Thanks! I fixed. In Moleculer v0.7.0 I removed the `ctx.user`. Intead there is `ctx.meta` to store session data. So I will rewrite it to store the logged in user in `ctx.meta.user`.
