### ISSUE TITLE
too many deprecated packages

### ISSUE THREAD

**Issue by Rajan** [icebob/vue-express-mongo-boilerplate#47]
npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated fs-promise@0.3.1: Use mz or fs-extra^3.0 with Promise Support

**Comment by icebob** [comment]
Dependencies updated in branch `ice-services`
