### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by lucduong** [icebob/vue-express-mongo-boilerplate#53]
Uncaught ReferenceError: webpackJsonp is not defined
    at frontend.js:1

This error occurs when I run as `production` mode.

**Comment by icebob** [comment]
Which branch?

**Comment by lucduong** [comment]
@icebob In master branch. I pulled the latest commit of master branch.

**Comment by icebob** [comment]
I updated dependencies and fix some issues. Try again.

**Comment by lucduong** [comment]
I pull the newest source but it still happened.
http://localhost:3000/login

![screen shot 2017-05-26 at 3 48 27 pm](https://cloud.githubusercontent.com/assets/2667418/26487761/03832a76-422b-11e7-85f8-f89d79d934ae.png)

**Comment by icebob** [comment]
Did you run `npm install` ?

2017-05-26 10:51 GMT+02:00 Duong Tuan Luc <notifications@github.com>:

**Comment by lucduong** [comment]
I'm using yarn and I tried 3 steps:

```
1. yarn
2. yarn build
3. yarn start
```

I will try to use npm instead of.

**Comment by lucduong** [comment]
@icebob `npm install` give the same result.

**Comment by icebob** [comment]
It's weird. Are there any webpack error in console during `build`?

**Comment by lucduong** [comment]
@icebob There is no error, build has done.

**Comment by icebob** [comment]
What was the solution?

**Comment by lucduong** [comment]
@icebob The issue wasn't solved yet. I said that "no error, build has done" for your question.
Everything fine except running at production got error.

**Comment by lucduong** [comment]
May I figured out why it happened in login page.

<img width="390" alt="screen shot 2017-05-29 at 2 36 33 pm" src="https://cloud.githubusercontent.com/assets/2667418/26540601/5601e546-447c-11e7-9103-eef06ebe97bb.png">

I added one more line before `frontend.js`

This is my bad.... `script(src='/app/vendor.js')`
