### ISSUE TITLE
CSS methodology

### ISSUE THREAD

**Issue by luiztsmelo** [icebob/vue-express-mongo-boilerplate#54]
Which CSS methodology did you use?

**Comment by icebob** [comment]
It's my custom CSS. I took ideas from bootstrap & bulma.

**Comment by luiztsmelo** [comment]
I liked it. More one question: How do I not have to import the style.scss in each component as you did? I'm trying to build a custom boilerplate to my project, based on yours. I tried to import only in the main App.vue, but it didn't work here.

**Comment by icebob** [comment]
You don't have to import the whole style.css to every components. If you want to use a variable just import the variables.scss. If you need a mixin, import the mixins.scss. Like [here](https://github.com/icebob/vue-express-mongo-boilerplate/blob/master/client/app/modules/posts/index.vue#L285)

**Comment by luiztsmelo** [comment]
Ok! Thanks
