### ISSUE TITLE
pb run dev

### ISSUE THREAD

**Issue by nlefebvre1410** [icebob/vue-express-mongo-boilerplate#60]
hi,
help my:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-express-mongo-boilerplate@0.9.0~predev: vue-express-mongo-boilerplate@0.9.0
6 silly lifecycle vue-express-mongo-boilerplate@0.9.0~predev: no script for predev, continuing
7 info lifecycle vue-express-mongo-boilerplate@0.9.0~dev: vue-express-mongo-boilerplate@0.9.0
8 verbose lifecycle vue-express-mongo-boilerplate@0.9.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue-express-mongo-boilerplate@0.9.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Applications/MAMP/htdocs/vue-express-mongo-boilerplate-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mongodb/bin
10 verbose lifecycle vue-express-mongo-boilerplate@0.9.0~dev: CWD: /Applications/MAMP/htdocs/vue-express-mongo-boilerplate-master
11 silly lifecycle vue-express-mongo-boilerplate@0.9.0~dev: Args: [ '-c', 'cross-env NODE_ENV=development nodemon --debug' ]
12 silly lifecycle vue-express-mongo-boilerplate@0.9.0~dev: Returned: code: 1  signal: null
13 info lifecycle vue-express-mongo-boilerplate@0.9.0~dev: Failed to exec dev script
14 verbose stack Error: vue-express-mongo-boilerplate@0.9.0 dev: `cross-env NODE_ENV=development nodemon --debug`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-express-mongo-boilerplate@0.9.0
16 verbose cwd /Applications/MAMP/htdocs/vue-express-mongo-boilerplate-master
17 error Darwin 16.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v7.8.0
20 error npm  v4.2.0`

**Comment by icebob** [comment]
Same as #31
