### ISSUE TITLE
on the landing page "Welcome To" should be "Welcome to Vue-Express-Mongo BoilerPlate"

### ISSUE THREAD

**Issue by utkarsh27a** [icebob/vue-express-mongo-boilerplate#63]
Hi,
  I just started using your boilerplate and I really liked it. This is wonderful and full of diversity with a good architecture.
      I saw a minor bug on the landing page, it displays "Welcome To" and it should be "Welcome to Vue-Express-Mongo BoilerPlate", I corrected it by enclosing app variable in braces at **/server/views/index.pug** on line no 9.
it would be

`h1=t("welcomeTo", {app})`

**Comment by icebob** [comment]
Thanks. Could you make a PR?

**Comment by utkarsh27a** [comment]
I am not able to push my code to the new branch.

**Comment by icebob** [comment]
What is the problem?

**Comment by simon1tan** [comment]
Please close this as it looks to be fixed
