### ISSUE TITLE
'npm run dev' does not work

### ISSUE THREAD

**Issue by goleh** [icebob/vue-express-mongo-boilerplate#65]
Hi, help me please with running it in dev mode. npm start works perfectly but npm run dev gives an error and i can't understand what is wrong.
Here is log:

0 info it worked if it ends with ok
1 verbose cli [ '/home/superoleh/.nvm/versions/node/v8.1.4/bin/node',
1 verbose cli   '/home/superoleh/.nvm/versions/node/v8.1.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v8.1.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-express-mongo-boilerplate@0.9.0~predev: vue-express-mongo-boilerplate@0.9.0
6 info lifecycle vue-express-mongo-boilerplate@0.9.0~dev: vue-express-mongo-boilerplate@0.9.0
7 verbose lifecycle vue-express-mongo-boilerplate@0.9.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-express-mongo-boilerplate@0.9.0~dev: PATH: /home/superoleh/.nvm/versions/node/v8.1.4/lib/node_modules/npm/bin/node-gyp-bin:/home/superoleh/Projects/vue-express-mongo-boilerplate/node_modules/.bin:/home/superoleh/.nvm/versions/node/v8.1.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/superoleh/.go/bin
9 verbose lifecycle vue-express-mongo-boilerplate@0.9.0~dev: CWD: /home/superoleh/Projects/vue-express-mongo-boilerplate
10 silly lifecycle vue-express-mongo-boilerplate@0.9.0~dev: Args: [ '-c', 'cross-env NODE_ENV=development nodemon --debug' ]
11 silly lifecycle vue-express-mongo-boilerplate@0.9.0~dev: Returned: code: 1  signal: null
12 info lifecycle vue-express-mongo-boilerplate@0.9.0~dev: Failed to exec dev script
13 verbose stack Error: vue-express-mongo-boilerplate@0.9.0 dev: `cross-env NODE_ENV=development nodemon --debug`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/superoleh/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/superoleh/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid vue-express-mongo-boilerplate@0.9.0
15 verbose cwd /home/superoleh/Projects/vue-express-mongo-boilerplate
16 verbose Linux 4.9.0-3-amd64
17 verbose argv "/home/superoleh/.nvm/versions/node/v8.1.4/bin/node" "/home/superoleh/.nvm/versions/node/v8.1.4/bin/npm" "run" "dev"
18 verbose node v8.1.4
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-express-mongo-boilerplate@0.9.0 dev: `cross-env NODE_ENV=development nodemon --debug`
22 error Exit status 1
23 error Failed at the vue-express-mongo-boilerplate@0.9.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by icebob** [comment]
Did you install `nodemon`?

**Comment by goleh** [comment]
Thanks, that was the problem. I just thought it is in the dev dependencies and forgot to checkout. It would be helpful to mention in the description the need of installing nodemon globally though. The project is great, thanks for your efforts!
