### ISSUE TITLE
npm run dev error...

### ISSUE THREAD

**Issue by sizz1324** [icebob/vue-express-mongo-boilerplate#72]
i just install and run npm run dev pop this error

$ npm run dev

> vue-express-mongo-boilerplate@0.9.0 dev D:\vue\theone\vue-express-mongo-boilerplate
> cross-env NODE_ENV=development nodemon --debug

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: D:\vue\theone\vue-express-mongo-boilerplate\server/**/* config.js webpack.*.config.js
[nodemon] starting `node --debug server/index.js`
(node:14892) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
[nodemon] app crashed - waiting for file changes before starting...

someone help me...

**Comment by drginm** [comment]
What version of node are you using?
I had the same issue with the latest version of node (v8), if you use 6 or 7 it should work.

**Comment by icebob** [comment]
I think, you need to follow the instructions in the warning: 
"DeprecationWarning: node --debug and node --debug-brk are invalid. Please use **node --inspect or node --inspect-brk** instead."

**Comment by sizz1324** [comment]
i use 8 version...

node --inspect or node --inspect-brk instead." this command does not working.

do i must reinstall node 6?

**Comment by sizz1324** [comment]
i change to v 6 and it run! thank you.

and thankyou icebob!

**Comment by Aparus** [comment]
I had same problem. Then I replaced two --debug in pachage.json to --inspect  (after @icebob advice), then appears this: 
(is there a way to fix this without downgrade node (v8.2.1)? 
![screenshot from 2017-09-06 04-27-59](https://user-images.githubusercontent.com/1222611/30090395-d4592cc8-92bb-11e7-9170-7058684f42b2.png)

**Comment by icebob** [comment]
@Aparus It is an other issue. Your port 3000 is in use.

**Comment by icebob** [comment]
You need to install MongoDB server locally. Download and install it. Or run it in Docker.

**Comment by Aparus** [comment]
@icebob thank you. I launched the boilerplate ) all works good. Now turn to learn vue and express )
