### ISSUE TITLE
What is this function ?  t("welcomeTo", {app}) 

### ISSUE THREAD

**Issue by StaticSpark** [icebob/vue-express-mongo-boilerplate#84]
server\views\index.pug

It seems like the t function is in vendor.js.. What does it do?

block content
	.page
		h1=t("welcomeTo", {app})

**Comment by icebob** [comment]
The `t` is the translate function for i18n.

https://github.com/icebob/vue-express-mongo-boilerplate/blob/master/server/core/express.js#L160
